all:
  hosts:
    salom:
      ansible_host: ec2-3-235-151-55.compute-1.amazonaws.com
      ansible_port: 22
      ansible_user: ec2-user
      ansible_ssh_private_key_file: /Users/salmaelmoataz/.ssh/id_rsa