-  hosts: salom
   remote_user: root
   become: yes
   tasks:
    - name: update all packages
      yum:
        name: '*'
        state: latest

    - name: install apache
      yum: 
        name: httpd
        state: installed
    - name: start apache
      service: 
        name: httpd
        state: started 
    - name: enable apache
      service: 
        name: httpd
        enabled: yes 

    - name: Install php
      yum:
        name: php  
        state: installed
    - name: start php
      service: 
        name: php-fpm
        state: started 
    - name: enable php
      service: 
        name: php-fpm
        enabled: yes 
    
    - name: install mysql
      yum: 
        name: 
        - mariadb-server
        state: installed 
    - name: start mysql
      service: 
        name: mariadb
        state: started 
    - name: enable mysql
      service: 
        name: mariadb
        enabled: yes 
    - name: copy file php
      copy:
       src: /Users/salmaelmoataz/Documents/provisioner/phpscript.php
       dest: /var/www/html

    - name: install firewall
      yum: 
        name: firewalld
        state: installed 
    - name: start firewalld
      service:
        name: firewalld
        state: started
    - name: enable firewalld
      service:
        name: firewalld
        enabled: yes

    - name: enable 80
      firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled
    - name: enable 443
      firewalld:
        port: 443/tcp
        permanent: yes
        state: enabled

        

      
